apiVersion: v1
kind: Service
metadata:
  name: azure-web-app
  namespace: azure-web
spec:
  type: LoadBalancer
  selector:
    app: azure-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
